# Generated by Django 5.0.3 on 2024-04-06 09:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminhome', '0003_destination_catmodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='DestinationModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Destination', models.CharField(max_length=20, null=True)),
                ('Category', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='adminhome.destination_catmodel')),
                ('District', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='adminhome.districtmodel')),
                ('Location', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='adminhome.locationmodel')),
                ('siate', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='adminhome.statemodel')),
            ],
        ),
    ]
