# Generated by Django 5.0.3 on 2024-04-06 09:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminhome', '0004_destinationmodel'),
    ]

    operations = [
        migrations.RenameField(
            model_name='destinationmodel',
            old_name='siate',
            new_name='state',
        ),
    ]
