# Generated by Django 5.0.3 on 2024-04-06 09:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminhome', '0005_rename_siate_destinationmodel_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='destinationmodel',
            name='Category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminhome.destination_catmodel'),
        ),
        migrations.AlterField(
            model_name='destinationmodel',
            name='District',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminhome.districtmodel'),
        ),
        migrations.AlterField(
            model_name='destinationmodel',
            name='Location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminhome.locationmodel'),
        ),
        migrations.AlterField(
            model_name='destinationmodel',
            name='state',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminhome.statemodel'),
        ),
    ]
